### ISSUE TITLE
Indicating Memory Leak for Resend Button

### ISSUE THREAD

**Issue by nvalakunde** [iamyogik/argon_buttons_flutter#11]
E/flutter ( 9119): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: setState() called after dispose(): _ArgonTimerButtonState#e0c68(lifecycle state: defunct, not mounted, tickers: tracking 0 tickers)
E/flutter ( 9119): This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
E/flutter ( 9119): The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
E/flutter ( 9119): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().

E/flutter ( 9119): #0      State.setState.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1204
E/flutter ( 9119): #1      State.setState 
package:flutter/…/widgets/framework.dart:1239
E/flutter ( 9119): #2      _ArgonTimerButtonState.startTimer.<anonymous closure> 
package:argon_buttons_flutter/argon_buttons_flutter.dart:372
E/flutter ( 9119): #3      _rootRunUnary  (dart:async/zone.dart:1198:47)
E/flutter ( 9119): #4      _CustomZone.runUnary  (dart:async/zone.dart:1100:19)
E/flutter ( 9119): #5      _CustomZone.runUnaryGuarded  (dart:async/zone.dart:1005:7)
E/flutter ( 9119): #6      _CustomZone.bindUnaryCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:1042:26)
E/flutter ( 9119): #7      _rootRunUnary  (dart:async/zone.dart:1206:13)
E/flutter ( 9119): #8      _CustomZone.runUnary  (dart:async/zone.dart:1100:19)
E/flutter ( 9119): #9      _CustomZone.bindUnaryCallback.<anonymous closure>  (dart:async/zone.dart:1026:26)
E/flutter ( 9119): #10     _Timer._runTimers  (dart:isolate-patch/timer_impl.dart:397:19)
E/flutter ( 9119): #11     _Timer._handleMessage  (dart:isolate-patch/timer_impl.dart:428:5)

**Comment by romathebest** [comment]
need to cancel timer in dispose method of _ArgonTimerButtonState:

  @override
  void dispose() {
    if (_timer != null) {
      _timer.cancel();
    }
    _controller.dispose();
    super.dispose();
  }
