### ISSUE TITLE
TimerButton issue

### ISSUE THREAD

**Issue by spporan** [iamyogik/argon_buttons_flutter#2]
The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
E/flutter (15177): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
E/flutter (15177): #0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1105:9)
E/flutter (15177): #1      State.setState (package:flutter/src/widgets/framework.dart:1140:6)
E/flutter (15177): #2      _ArgonTimerButtonState.startTimer.<anonymous closure> (package:argon_buttons_flutter/argon_buttons_flutter.dart:360:24)
E/flutter (15177): #3      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter (15177): #4      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (15177): #5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (15177): #6      _CustomZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:968:26)
E/flutter (15177): #7      _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (15177): #8      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (15177): #9      _CustomZone.bindUnaryCallback.<anonymous closure> (dart:async/zone.dart:952:26)
E/flutter (15177): #10     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
E/flutter (15177): #11     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
E/flutter (15177): #12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

This issue happen when timer button like Resend otp is working then click another button like submit then occur this issue. have any way to stop timer when need?

**Comment by tomatoset** [comment]
Try calling by pressing the button
startTimer(-1);
